import { useState, useEffect } from "react";
import { buildApiUrl } from "@/config/api";
import { HabitLoopLoginModal } from "@/components/HabitLoopLoginModal";
import { HabitLoopSignupModal } from "@/components/HabitLoopSignupModal";

interface HabitLoopUserModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export function HabitLoopUserModal({ open, onClose, onSuccess }: HabitLoopUserModalProps) {
  // Modal Orchestration - Single User Authentication Flow
  const [showLogin, setShowLogin] = useState(false);
  const [showSignup, setShowSignup] = useState(false);
  const [autoGeneratedUserId, setAutoGeneratedUserId] = useState<string>('');
  const [usingFallbackMode, setUsingFallbackMode] = useState(false);

  // User ID Generation - Auto-generates next user ID for new signups
  const generateNextUserId = async () => {
    try {
      // Get the next available user ID from backend
      const response = await fetch(buildApiUrl('habitloop/next-user-id'), {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' }
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.success && data.nextUserId) {
          setUsingFallbackMode(false);
          return data.nextUserId;
        }
      } else if (response.status === 500) {
        console.warn('Server error generating user ID, using fallback');
        setUsingFallbackMode(true);
      }
    } catch (error) {
      console.warn('Network error generating user ID, using fallback:', error);
      setUsingFallbackMode(true);
    }
    
    // Fallback: generate a timestamp-based ID when backend is unavailable
    const timestamp = Date.now();
    const fallbackId = `user-${timestamp}`;
    console.log('Using fallback user ID:', fallbackId);
    setUsingFallbackMode(true);
    return fallbackId;
  };

  // State Management - Manages which modal to show
  useEffect(() => {
    if (open) {
      // Generate next user ID for potential signup
      generateNextUserId().then(setAutoGeneratedUserId);
      setShowLogin(true); // Default to login modal
    } else {
      setShowLogin(false);
      setShowSignup(false);
    }
  }, [open]);

  // Retry mechanism when network comes back online
  useEffect(() => {
    if (usingFallbackMode) {
      const retryInterval = setInterval(async () => {
        try {
          const response = await fetch(buildApiUrl('health'), { method: 'GET' });
          if (response.ok) {
            console.log('Network restored, retrying user ID generation');
            const nextUserId = await generateNextUserId();
            setAutoGeneratedUserId(nextUserId);
          }
        } catch (error) {
          // Still offline, continue waiting
        }
      }, 10000); // Retry every 10 seconds

      return () => clearInterval(retryInterval);
    }
  }, [usingFallbackMode]);

  // Seamless transitions between modes
  const handleOpenSignup = () => {
    setShowLogin(false);
    setShowSignup(true);
  };



  // User Creation Handler - For new signups
  const handleUserCreated = async (_newUser: any) => {
    // Generate next user ID for future signups
    const nextUserId = await generateNextUserId();
    setAutoGeneratedUserId(nextUserId);
    
    // Switch back to login mode
    setShowSignup(false);
    setShowLogin(true);
  };

  const handleModalClose = () => {
    setShowLogin(false);
    setShowSignup(false);
    onClose();
  };

  return (
    <>
      {/* Network Status Indicator */}
      {usingFallbackMode && (
        <div className="fixed top-4 right-4 z-50 bg-red-100 border border-red-400 text-red-800 px-4 py-2 rounded-md shadow-lg">
          <div className="flex items-center gap-2">
            <i className="fas fa-exclamation-triangle"></i>
            <span className="text-sm font-medium">Offline Mode</span>
            <span className="text-xs">Read-only until connection restored</span>
          </div>
        </div>
      )}
      
      {/* Login Flow - Single User Authentication */}
      <HabitLoopLoginModal
        open={showLogin}
        onClose={handleModalClose}
        onSuccess={onSuccess}
        onOpenSignup={handleOpenSignup}
        autoGeneratedUserId={autoGeneratedUserId}
      />
      
      {/* Signup Flow - Create Account */}
      <HabitLoopSignupModal
        open={showSignup}
        onClose={handleModalClose}
        onSuccess={onSuccess}
        onUserCreated={handleUserCreated}
        autoGeneratedUserId={autoGeneratedUserId}
        disabled={usingFallbackMode}
      />
    </>
  );
}
