import { useState, useEffect } from "react";
import { buildApiUrl } from "@/config/api";
import { HabitLoopLoginModal } from "@/components/HabitLoopLoginModal";
import { HabitLoopSignupModal } from "@/components/HabitLoopSignupModal";
import type { HabitLoopUser } from "@/components/HabitLoopLoginModal";

interface HabitLoopUserModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

// Fallback users in case API fails
const FALLBACK_USERS: HabitLoopUser[] = [
  {
    id: "user-001",
    username: "user-001",
    firstName: "Alex",
    lastName: "Chen",
    difficulty: "medium",
    avatar: "👨‍💻",
    description: "Productivity enthusiast",
  },
];

export function HabitLoopUserModal({
  open,
  onClose,
  onSuccess,
}: HabitLoopUserModalProps) {
  // Modal Orchestration - Dual Mode
  const [showLogin, setShowLogin] = useState(false);
  const [showSignup, setShowSignup] = useState(false);
  const [users, setUsers] = useState<HabitLoopUser[]>([]);
  const [autoGeneratedUserId, setAutoGeneratedUserId] = useState<string>("");

  // User ID Generation - Auto-generates next user ID
  const generateNextUserId = (existingUsers: HabitLoopUser[]) => {
    // Extract all user IDs that start with 'user-'
    const userIds = existingUsers
      .map((user) => user.id)
      .filter((id) => id.startsWith("user-"));

    // First, look for the 6-digit format (user-000001, user-000002, etc.)
    const sixDigitIds = userIds.filter((id) => /^user-\d{6}$/.test(id));

    if (sixDigitIds.length > 0) {
      // Parse 6-digit format IDs
      const numbers = sixDigitIds.map((id) => {
        const numberPart = id.replace("user-", "");
        return parseInt(numberPart, 10);
      });
      const maxNumber = Math.max(...numbers);
      const nextNumber = maxNumber + 1;
      return `user-${nextNumber.toString().padStart(6, "0")}`;
    }

    // If no 6-digit format found, look for any user- format and find the highest
    const numbers = userIds.map((id) => {
      const numberPart = id.replace("user-", "");
      const parsed = parseInt(numberPart, 10);
      return isNaN(parsed) ? 0 : parsed;
    });
    const maxNumber = numbers.length > 0 ? Math.max(...numbers) : 0;
    const nextNumber = maxNumber + 1;

    // Always format as user-XXXXXX (6 digits with leading zeros)
    return `user-${nextNumber.toString().padStart(6, "0")}`;
  };

  // API Integration - Data Management
  const fetchUsers = async () => {
    try {
      const response = await fetch(buildApiUrl("habitloop/users"), {
        method: "GET",
        headers: { "Content-Type": "application/json" },
      });

      if (response.ok) {
        const data = await response.json();
        if (data.success && data.users) {
          setUsers(data.users);
          // Real-time Updates - Generate next user ID
          const nextUserId = generateNextUserId(data.users);
          setAutoGeneratedUserId(nextUserId);
        } else {
          // Error Handling - Graceful fallbacks for API failures
          setUsers(FALLBACK_USERS);
          setAutoGeneratedUserId("user-000001");
        }
      } else {
        setUsers(FALLBACK_USERS);
        setAutoGeneratedUserId("user-000001");
      }
    } catch (error) {
      // Network Issues - Connection error handling
      console.warn("Failed to fetch users:", error);
      setUsers(FALLBACK_USERS);
      setAutoGeneratedUserId("user-000001");
    }
  };

  // State Management - Manages which modal to show
  useEffect(() => {
    if (open) {
      fetchUsers();
      setShowLogin(true); // Default to login modal
    } else {
      setShowLogin(false);
      setShowSignup(false);
    }
  }, [open]);

  // Seamless transitions between modes
  const handleOpenSignup = () => {
    setShowLogin(false);
    setShowSignup(true);
  };

  // User List Management - Maintains user list state
  const handleUserCreated = (newUser: HabitLoopUser) => {
    // User List Updates - New users appear immediately
    if ((window as any).addNewUserToLogin) {
      (window as any).addNewUserToLogin(newUser);
    }

    // Generate next user ID for future signups
    const nextUserId = generateNextUserId([...users, newUser]);
    setAutoGeneratedUserId(nextUserId);

    // Modal State - Seamless transitions between modes
    setShowSignup(false);
    setShowLogin(true);
  };

  const handleModalClose = () => {
    setShowLogin(false);
    setShowSignup(false);
    onClose();
  };

  return (
    <>
      {/* Login Flow - User Selection Interface */}
      <HabitLoopLoginModal
        open={showLogin}
        onClose={handleModalClose}
        onSuccess={onSuccess}
        onOpenSignup={handleOpenSignup}
        autoGeneratedUserId={autoGeneratedUserId}
      />

      {/* Signup Flow - Create Account Button Integration */}
      <HabitLoopSignupModal
        open={showSignup}
        onClose={handleModalClose}
        onSuccess={onSuccess}
        onUserCreated={handleUserCreated}
        autoGeneratedUserId={autoGeneratedUserId}
      />
    </>
  );
}
