import { useState, useEffect, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { buildApiUrl } from "@/config/api";

// Types
export interface HabitLoopUser {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  difficulty: string;
  avatar: string;
  description: string;
  level?: number;
  xp?: number;
}

interface HabitLoopLoginModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  onOpenSignup: () => void;
  autoGeneratedUserId: string;
}

// Fallback users in case API fails
const FALLBACK_USERS: HabitLoopUser[] = [
  {
    id: "user-001",
    username: "user-001",
    firstName: "Alex",
    lastName: "Chen",
    difficulty: "medium",
    avatar: "👨‍💻",
    description: "Productivity enthusiast"
  }
];

export function HabitLoopLoginModal({ 
  open, 
  onClose, 
  onSuccess, 
  onOpenSignup, 
  autoGeneratedUserId 
}: HabitLoopLoginModalProps) {
  const { toast } = useToast();
  const { loginAsHabitLoopUser } = useAuth();
  const dialogContentRef = useRef<HTMLDivElement>(null);
  
  // User management state
  const [selectedUser, setSelectedUser] = useState<HabitLoopUser | null>(null);
  const [password, setPassword] = useState('');
  const [showPasswordField, setShowPasswordField] = useState(false);
  const [showLoginPassword, setShowLoginPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<HabitLoopUser[]>([]);
  const [userData, setUserData] = useState<Record<string, { level: number; xp: number }>>({});
  const [fetchingData] = useState<Record<string, boolean>>({});
  const [fetchingUsers, setFetchingUsers] = useState(false);
  const [newlyCreatedUser, setNewlyCreatedUser] = useState<string | null>(null);
  const [isTransitioning, setIsTransitioning] = useState(false);

  // Enhanced scroll animation with consistent timing
  const scrollToPasswordSection = () => {
    if (!dialogContentRef.current) return;
    
    setIsTransitioning(true);
    
    // Use requestAnimationFrame for smooth scrolling
    requestAnimationFrame(() => {
      const passwordSection = dialogContentRef.current?.querySelector('#password-section') as HTMLElement;
      const container = dialogContentRef.current;
      
      if (passwordSection && container) {
        // Calculate the scroll position
        const containerRect = container.getBoundingClientRect();
        const sectionRect = passwordSection.getBoundingClientRect();
        const scrollTop = container.scrollTop;
        const targetScrollTop = scrollTop + (sectionRect.top - containerRect.top) - 20; // 20px offset
        
        // Smooth scroll with consistent timing
        container.scrollTo({
          top: targetScrollTop,
          behavior: 'smooth'
        });
        
        // Add visual feedback after scroll
        setTimeout(() => {
          passwordSection.classList.add(
            'shadow-xl', 'shadow-blue-200/60', 
            'ring-2', 'ring-blue-400', 'ring-opacity-70'
          );
          
          // Remove highlighting after delay
          setTimeout(() => {
            passwordSection.classList.remove(
              'shadow-xl', 'shadow-blue-200/60', 
              'ring-2', 'ring-blue-400', 'ring-opacity-70'
            );
          }, 2000);
        }, 600); // Wait for scroll to complete
      }
      
      setIsTransitioning(false);
    });
  };

  // Fetch all users from backend
  const fetchUsers = async () => {
    if (fetchingUsers) return;
    
    setFetchingUsers(true);
    
    try {
      const response = await fetch(buildApiUrl('habitloop/users'), {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' }
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.success && data.users) {
          setUsers(data.users);
          // Extract user data (level, XP) from the users array
          const userDataMap: Record<string, { level: number; xp: number }> = {};
          data.users.forEach((user: HabitLoopUser) => {
            userDataMap[user.id] = {
              level: user.level || 1,
              xp: user.xp || 0
            };
          });
          setUserData(userDataMap);
        } else {
          setUsers(FALLBACK_USERS);
        }
      } else {
        setUsers(FALLBACK_USERS);
      }
    } catch (error) {
      console.warn('Failed to fetch users:', error);
      setUsers(FALLBACK_USERS);
    } finally {
      setFetchingUsers(false);
    }
  };

  // Enhanced user selection with better UX
  const handleUserSelect = (user: HabitLoopUser) => {
    setSelectedUser(user);
    setShowPasswordField(true);
    setPassword('');
    setShowLoginPassword(false);
    
    // Scroll to password section with consistent timing
    setTimeout(() => {
      scrollToPasswordSection();
    }, 100);
  };

  const handleHabitLoopUserSelect = async (user: HabitLoopUser) => {
    if (!password.trim()) {
      toast({
        title: "Password Required",
        description: "Please enter the password for this user.",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      // JWT Token Management & Authentication
      await loginAsHabitLoopUser({ ...user, password });
      
      toast({
        title: "Welcome to HabitLoop! 🎉",
        description: `Logged in as ${user.firstName} ${user.lastName}`,
      });
      
      // Reset form state
      setSelectedUser(null);
      setShowPasswordField(false);
      setPassword('');
      
      onSuccess();
    } catch (error) {
      toast({
        title: "Login failed",
        description: error instanceof Error ? error.message : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  // Enhanced back navigation
  const handleBackToUserSelection = () => {
    setIsTransitioning(true);
    
    // Smooth transition back to user selection
    setTimeout(() => {
      setSelectedUser(null);
      setShowPasswordField(false);
      setPassword('');
      setShowLoginPassword(false);
      setIsTransitioning(false);
      
      // Scroll back to top
      const container = dialogContentRef.current;
      if (container) {
        container.scrollTo({
          top: 0,
          behavior: 'smooth'
        });
      }
    }, 150);
  };

  // Reset state when modal opens/closes
  useEffect(() => {
    if (open) {
      fetchUsers();
      setSelectedUser(null);
      setShowPasswordField(false);
      setPassword('');
      setShowLoginPassword(false);
      setIsTransitioning(false);
    }
  }, [open]);

  // Difficulty color coding
  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case "easy":
        return "bg-green-100 text-green-800 border-green-200";
      case "medium":
        return "bg-yellow-100 text-yellow-800 border-yellow-200";
      case "hard":
        return "bg-red-100 text-red-800 border-red-200";
      default:
        return "bg-gray-100 text-gray-800 border-gray-200";
    }
  };

  // Handle new user creation from signup
  const addNewUser = (user: HabitLoopUser) => {
    setUsers(prevUsers => [user, ...prevUsers]);
    setNewlyCreatedUser(user.id);
    
    // Remove highlighting after 5 seconds
    setTimeout(() => {
      setNewlyCreatedUser(null);
    }, 5000);
  };

  // Expose method to parent component via window (temporary solution)
  useEffect(() => {
    (window as any).addNewUserToLogin = addNewUser;
    return () => {
      delete (window as any).addNewUserToLogin;
    };
  }, []);

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent 
        ref={dialogContentRef}
        className={`max-w-4xl max-h-[80vh] overflow-y-auto transition-all duration-300 ${
          showPasswordField ? 'max-w-2xl' : 'max-w-4xl'
        }`}
      >
        <DialogHeader>
          <div className="text-center">
            {/* Gradient Design */}
            <div className="w-16 h-16 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <i className="fas fa-users text-white text-2xl"></i>
            </div>
            <DialogTitle className="text-2xl font-bold text-gray-900 mb-2">
              {showPasswordField ? `Login as ${selectedUser?.firstName}` : "Try as a HabitLoop User"}
            </DialogTitle>
            <DialogDescription className="text-gray-600 mb-6">
              {showPasswordField 
                ? `Please enter the password for ${selectedUser?.firstName} ${selectedUser?.lastName}'s account.`
                : "Experience HabitLoop with pre-configured user profiles or create your own account. Each user has different habits, streaks, and progress to demonstrate the full range of features."
              }
            </DialogDescription>
          </div>
        </DialogHeader>

        {/* Signup Flow Integration - Only show when not in login mode */}
        {!showPasswordField && (
          <div className="mb-6">
            <Button
              onClick={onOpenSignup}
              className="w-full bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white py-3 text-lg font-semibold"
            >
              <i className="fas fa-plus mr-2"></i>
              Create New User Account
            </Button>
            {/* Next User ID Display */}
            {autoGeneratedUserId && (
              <p className="text-center text-xs text-gray-500 mt-2">
                (Next: {autoGeneratedUserId})
              </p>
            )}
          </div>
        )}

        {/* User Grid Display - Only show when not in login mode */}
        {!showPasswordField && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {fetchingUsers ? (
              <div className="col-span-full text-center py-8">
                <div className="flex items-center justify-center">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mr-3"></div>
                  <span className="text-gray-600">Loading users...</span>
                </div>
              </div>
            ) : users.length === 0 ? (
              <div className="col-span-full text-center py-8">
                <div className="text-gray-500">
                  <i className="fas fa-users text-4xl mb-4 text-gray-300"></i>
                  <p>No users available</p>
                </div>
              </div>
            ) : (
              users.map((user) => (
                <Card 
                  key={user.id}
                  className={`cursor-pointer transition-all duration-200 hover:shadow-lg hover:scale-105 border-2 ${
                    selectedUser?.id === user.id 
                      ? 'border-indigo-500 bg-indigo-50' 
                      : newlyCreatedUser === user.id
                      ? 'border-green-500 bg-green-50 animate-pulse'
                      : 'border-gray-200 hover:border-indigo-300'
                  }`}
                  onClick={() => setSelectedUser(user)}
                >
                  <CardContent className="p-6">
                    <div className="text-center">
                      {/* Avatar Display */}
                      <div className="mb-3">
                        {user.avatar && user.avatar.startsWith('http') ? (
                          <img
                            src={user.avatar}
                            alt={`${user.firstName} ${user.lastName}'s avatar`}
                            className="w-16 h-16 mx-auto rounded-full border-2 border-gray-200 shadow-sm"
                          />
                        ) : (
                          <div className="text-4xl">{user.avatar || '👤'}</div>
                        )}
                      </div>
                      
                      {/* User Information Display */}
                      <h3 className="text-lg font-semibold text-gray-900 mb-1">
                        {user.firstName} {user.lastName}
                      </h3>
                      <p className="text-sm text-gray-500 mb-3">{user.username}</p>
                      
                      {/* New User Highlighting */}
                      {newlyCreatedUser === user.id && (
                        <div className="mb-2">
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                            ✨ New User
                          </span>
                        </div>
                      )}
                      
                      {/* User Statistics - Real-time Data */}
                      <div className="space-y-2 mb-4">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Level:</span>
                          <span className="font-semibold text-indigo-600">
                            {fetchingData[user.id] ? (
                              <span className="text-gray-500">Loading...</span>
                            ) : userData[user.id] ? (
                              userData[user.id].level
                            ) : (
                              <span className="text-gray-400">-</span>
                            )}
                          </span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">XP:</span>
                          <span className="font-semibold text-purple-600">
                            {fetchingData[user.id] ? (
                              <span className="text-gray-500">Loading...</span>
                            ) : userData[user.id] ? (
                              userData[user.id].xp.toLocaleString()
                            ) : (
                              <span className="text-gray-400">-</span>
                            )}
                          </span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Difficulty:</span>
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${getDifficultyColor(user.difficulty)}`}>
                            {user.difficulty}
                          </span>
                        </div>
                      </div>
                      
                      <p className="text-xs text-gray-600 mb-4">{user.description}</p>
                      
                      {/* Visual Feedback & Selection States */}
                      {selectedUser?.id === user.id ? (
                        <div className="w-full bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 px-3 py-2 rounded-md text-center text-sm font-medium">
                          <i className="fas fa-check mr-2"></i>
                          Selected
                        </div>
                      ) : (
                        <Button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleUserSelect(user);
                          }}
                          disabled={loading || isTransitioning}
                          className="w-full bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white transform hover:scale-105 transition-all duration-200"
                        >
                          <i className="fas fa-sign-in-alt mr-2"></i>
                          Login as {user.firstName}
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))
            )}
          </div>
        )}

        {/* Password-based Login - Enhanced UX with focused popup */}
        {showPasswordField && selectedUser && (
          <div 
            id="password-section" 
            className={`mt-6 p-6 bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 rounded-lg border-2 border-indigo-300 dark:border-indigo-600 shadow-lg transform transition-all duration-500 ease-out hover:shadow-xl hover:scale-[1.02] hover:border-indigo-400 ${
              isTransitioning ? 'opacity-0 scale-95' : 'opacity-100 scale-100'
            }`}
          >
            <div className="text-center mb-4">
              <div className="flex items-center justify-center mb-2">
                <div className="w-8 h-8 bg-indigo-100 dark:bg-indigo-800 rounded-full flex items-center justify-center mr-3">
                  <i className="fas fa-lock text-indigo-600 dark:text-indigo-300 text-sm"></i>
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                  Login as {selectedUser.firstName} {selectedUser.lastName}
                </h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Please enter the password for this account
              </p>
            </div>
            
            <div className="space-y-4">
              <div>
                <Label htmlFor="loginPassword" className="text-sm font-medium">
                  Password
                </Label>
                <div className="relative mt-1">
                  <Input
                    id="loginPassword"
                    type={showLoginPassword ? "text" : "password"}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your password"
                    className="pr-10"
                    autoFocus
                    onKeyPress={(e) => {
                      if (e.key === 'Enter') {
                        handleHabitLoopUserSelect(selectedUser);
                      }
                    }}
                  />
                  {/* Password Visibility Toggle */}
                  <button
                    type="button"
                    onClick={() => setShowLoginPassword(!showLoginPassword)}
                    className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400 transition-all duration-200 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 rounded-full p-1"
                    title={showLoginPassword ? "Hide password" : "Show password"}
                  >
                    <i className={`fas ${showLoginPassword ? 'fa-eye-slash' : 'fa-eye'} text-sm`}></i>
                  </button>
                </div>
              </div>
              
              <div className="flex gap-3">
                <Button
                  onClick={() => handleHabitLoopUserSelect(selectedUser)}
                  disabled={loading || !password.trim()}
                  className="flex-1 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white"
                >
                  {loading ? (
                    <div className="flex items-center">
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                      Logging in...
                    </div>
                  ) : (
                    <>
                      <i className="fas fa-sign-in-alt mr-2"></i>
                      Login
                    </>
                  )}
                </Button>
                
                <Button
                  onClick={handleBackToUserSelection}
                  variant="outline"
                  disabled={loading || isTransitioning}
                  className="px-4"
                >
                  <i className="fas fa-arrow-left mr-2"></i>
                  Back to Users
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Demo Note - Only show when not in login mode */}
        {!showPasswordField && (
          <div className="text-center mt-6">
            <p className="text-sm text-gray-500">
              These are demo accounts with pre-configured data to showcase HabitLoop's features.
            </p>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
