import { useState, useEffect } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { useIsMobile } from "@/hooks/use-mobile";
import { buildApiUrl } from "@/config/api";
import { AIQuestionnaireModal } from "@/components/AIQuestionnaireModal";

// Feature constants
const DIFFICULTY_OPTIONS = [
  { value: 'easy', label: 'Easy - Beginner friendly', description: 'Perfect for starting your habit journey' },
  { value: 'medium', label: 'Medium - Balanced challenge', description: 'Great for consistent habit builders' },
  { value: 'hard', label: 'Hard - Advanced user', description: 'For experienced habit masters' },
];

const AVATAR_STYLES = [
  { value: 'adventurer', label: 'Adventurer', description: 'Fantasy-style characters' },
  { value: 'avataaars', label: 'Avataaars', description: 'Cartoon-style people' },
  { value: 'bottts', label: 'Bottts', description: 'Robot characters' },
  { value: 'fun-emoji', label: 'Fun Emoji', description: 'Expressive emoji faces' },
  { value: 'lorelei', label: 'Lorelei', description: 'Abstract geometric patterns' },
  { value: 'personas', label: 'Personas', description: 'Professional avatars' },
  { value: 'notionists', label: 'Notionists', description: 'Minimalist designs' },
];

// Types
export interface HabitLoopUser {
  id: string; username: string; firstName: string; lastName: string;
  difficulty: string; avatar: string; description: string;
}
interface SignupFormData {
  userId: string; firstName: string; lastName: string; email: string; password: string;
  confirmPassword: string; difficulty: 'easy' | 'medium' | 'hard'; profileImageUrl: string;
  avatarStyle: string; avatarSeed: string; bio: string; goals: string[];
}
interface HabitLoopSignupModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  onUserCreated: (user: HabitLoopUser) => void;
  autoGeneratedUserId: string;
  disabled?: boolean;
}

// DiceBear avatar URL generator
const generateAvatarUrl = (style: string, seed: string, size = 128) =>
  `https://api.dicebear.com/7.x/${style}/svg?seed=${encodeURIComponent(seed)}&size=${size}`;

export function HabitLoopSignupModal({
  open, onClose, onSuccess, onUserCreated, autoGeneratedUserId, disabled = false
}: HabitLoopSignupModalProps) {
  const { toast } = useToast();
  const { loginAsHabitLoopUser } = useAuth();
  const isMobile = useIsMobile();
  const [currentStep, setCurrentStep] = useState(1);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [showAIQuestionnaire, setShowAIQuestionnaire] = useState(false);
  const [loading, setLoading] = useState(false);
  const [questionnaireCompleted, setQuestionnaireCompleted] = useState(false);

  // form state; resets when modal closes
  const [signupFormData, setSignupFormData] = useState<SignupFormData>({
    userId: autoGeneratedUserId, firstName: '', lastName: '', email: '',
    password: '', confirmPassword: '', difficulty: 'medium', profileImageUrl: '',
    avatarStyle: 'avataaars', avatarSeed: 'HabitLoop', bio: '', goals: [],
  });
  useEffect(() => {
    if (autoGeneratedUserId) {
      setSignupFormData(f => ({ ...f, userId: autoGeneratedUserId }));
    }
  }, [autoGeneratedUserId]);
  useEffect(() => {
    if (!open) {
      setCurrentStep(1);
      setShowPassword(false);
      setShowConfirmPassword(false);
      setSignupFormData({
        userId: autoGeneratedUserId, firstName: '', lastName: '', email: '',
        password: '', confirmPassword: '', difficulty: 'medium', profileImageUrl: '',
        avatarStyle: 'avataaars', avatarSeed: 'HabitLoop', bio: '', goals: [],
      });
    }
  }, [open, autoGeneratedUserId]);

  // Handlers
  const handleInputChange = (field: keyof SignupFormData, value: string | string[]) => {
    setSignupFormData(prev => ({ ...prev, [field]: value }));
    if (field === 'firstName' && typeof value === 'string' && value.trim()) {
      setSignupFormData(prev => ({
        ...prev, avatarSeed: value.trim() + (prev.lastName ? ' ' + prev.lastName : '')
      }));
    }
  };

  const handleAvatarStyleChange = (style: string) =>
    setSignupFormData(prev => ({ ...prev, avatarStyle: style }));
  const handleAvatarSeedChange = (seed: string) =>
    setSignupFormData(prev => ({ ...prev, avatarSeed: seed }));
  const generateRandomSeed = () =>
    setSignupFormData(prev => ({ ...prev, avatarSeed: Math.random().toString(36).substring(2, 15) }));
  const getCurrentAvatarUrl = () =>
    generateAvatarUrl(signupFormData.avatarStyle, signupFormData.avatarSeed, 128);

  const validateStep1 = () => {
    if (!signupFormData.firstName.trim() || !signupFormData.lastName.trim()) {
      toast({ title: "Name Required", description: "Please enter your first and last name.", variant: "destructive" }); return false;
    }
    if (!signupFormData.email.trim() || !signupFormData.email.includes('@')) {
      toast({ title: "Valid Email Required", description: "Please enter a valid email address.", variant: "destructive" }); return false;
    }
    return true;
  };
  const validateStep2 = () => {
    if (signupFormData.password.length < 6) {
      toast({ title: "Password Too Short", description: "Password must be at least 6 characters long.", variant: "destructive" }); return false;
    }
    if (signupFormData.password !== signupFormData.confirmPassword) {
      toast({ title: "Passwords Don't Match", description: "Please make sure your passwords match.", variant: "destructive" }); return false;
    }
    return true;
  };

  const handleNext = () => {
    if (currentStep === 1 && !validateStep1()) return;
    if (currentStep === 2 && !validateStep2()) return;
    setCurrentStep(prev => Math.min(prev + 1, 3));
  };
  const handleBack = () => setCurrentStep(prev => Math.max(prev - 1, 1));

  const handleSignupSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setLoading(true);
    try {
      // Get AI recommendations from localStorage if available
      let aiRecommendations = null;
      const storedRecommendations = localStorage.getItem('habitRecommendations');
      if (storedRecommendations) {
        try {
          aiRecommendations = JSON.parse(storedRecommendations);
          console.log('Including AI recommendations in signup:', aiRecommendations.length);
        } catch (error) {
          console.error('Error parsing stored recommendations:', error);
        }
      }

      // Get questionnaire data from localStorage if available
      let questionnaireData = null;
      const storedQuestionnaire = localStorage.getItem('questionnaireData');
      if (storedQuestionnaire) {
        try {
          questionnaireData = JSON.parse(storedQuestionnaire);
          console.log('Including questionnaire data in signup');
        } catch (error) {
          console.error('Error parsing stored questionnaire:', error);
        }
      }

      const response = await fetch(buildApiUrl('habitloop/signup'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: signupFormData.userId,
          firstName: signupFormData.firstName,
          lastName: signupFormData.lastName,
          email: signupFormData.email,
          password: signupFormData.password,
          difficulty: signupFormData.difficulty,
          profileImageUrl: getCurrentAvatarUrl(),
          bio: signupFormData.bio, 
          goals: signupFormData.goals,
          questionnaireData: questionnaireData,
          aiRecommendations: aiRecommendations,
        }),
      });
      if (response.ok) {
        const responseData = await response.json();
        toast({ title: "Account Created Successfully! 🎉", description: `Welcome ${signupFormData.firstName}! Your account has been created.` });
        const newUser: HabitLoopUser = {
          id: signupFormData.userId, username: signupFormData.userId,
          firstName: signupFormData.firstName, lastName: signupFormData.lastName,
          difficulty: signupFormData.difficulty, avatar: '🆕',
          description: `New user - ${signupFormData.difficulty} difficulty`
        };
        onUserCreated(newUser);
        if (responseData.success && responseData.user) {
          try {
            await loginAsHabitLoopUser(newUser); onSuccess();
          } catch (error) { /* silent - manual login fallback */ }
        }
        onClose();
      } else {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to create account');
      }
    } catch (error) {
      toast({ title: "Signup Failed", description: error instanceof Error ? error.message : "Failed to create account. Please try again.", variant: "destructive" });
    } finally { setLoading(false); }
  };

  const getStepTitle = () => ["Basic Information", "Security Setup", "Personalization"][currentStep - 1] || "Create New User";
  const getStepDescription = () =>
    ["Tell us about yourself", "Create a secure password", "Customize your experience"][currentStep - 1] || "";

  return (
    <>
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className={`
          sm:max-w-[600px] max-h-[90vh] overflow-y-auto
          ${isMobile ? 'w-[95vw] max-w-[95vw] mx-2' : 'w-full'} p-4 sm:p-6
        `}>
          <DialogHeader className="space-y-3">
            <DialogTitle className="text-xl sm:text-2xl font-semibold text-gray-900 dark:text-gray-100 text-center sm:text-left">
              {getStepTitle()}
            </DialogTitle>
            <p className="text-sm sm:text-base text-gray-600 dark:text-gray-400 text-center sm:text-left">
              {getStepDescription()}
            </p>
            
            {/* Offline Mode Warning */}
            {disabled && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-3">
                <div className="flex items-center gap-2 text-red-800">
                  <i className="fas fa-exclamation-triangle"></i>
                  <span className="text-sm font-medium">Offline Mode</span>
                </div>
                <p className="text-xs text-red-700 mt-1">
                  Account creation is disabled until network connection is restored. Please wait for the connection to return.
                </p>
              </div>
            )}
          </DialogHeader>
          {/* Stepper & steps */}
          <div className="flex items-center justify-center space-x-1 sm:space-x-2 mb-4 sm:mb-6">
            {[1, 2, 3].map((step) => (
              <div key={step} className="flex items-center">
                <div
                  className={`
                    w-6 h-6 sm:w-8 sm:h-8 rounded-full flex items-center justify-center 
                    text-xs sm:text-sm font-medium transition-all duration-200
                    ${step <= currentStep
                      ? 'bg-blue-600 text-white shadow-md'
                      : 'bg-gray-200 dark:bg-gray-700 text-gray-500'
                    }
                  `}
                >
                  {step < currentStep ? '✓' : step}
                </div>
                {step < 3 && (
                  <div
                    className={`
                      w-8 sm:w-12 h-1 mx-1 sm:mx-2 transition-all duration-200
                      ${step < currentStep ? 'bg-blue-600' : 'bg-gray-200 dark:bg-gray-700'}
                    `}
                  />
                )}
              </div>
            ))}
          </div>

          <div className="space-y-4 sm:space-y-6">
            {/* Step 1: Basic Info */}
            {currentStep === 1 && (
              <div className="space-y-4">
                {/* User ID & Difficulty */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="signup-userId">User ID *</Label>
                    <div className="relative flex items-center">
                      <Input 
                      id="signup-userId" 
                      name="userId"
                      value={signupFormData.userId} 
                      readOnly 
                      disabled={disabled}
                      className="h-10 sm:h-11 text-sm bg-gray-100 pr-12 disabled:opacity-50" 
                    />
                      <span className="absolute right-3 text-xs py-1 px-2 rounded font-semibold bg-blue-100 text-blue-600 border border-blue-200" aria-label="Auto-generated">
                        Auto
                      </span>
                    </div>
                    <p className="text-xs text-gray-500 dark:text-gray-400">Auto-generated unique identifier</p>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="difficulty">Difficulty Level</Label>
                    <Select
                      value={signupFormData.difficulty}
                      onValueChange={(v) => handleInputChange('difficulty', v as any)}
                    >
                      <SelectTrigger id="difficulty" name="difficulty" className="h-10 sm:h-11 text-sm"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {DIFFICULTY_OPTIONS.map(option => (
                          <SelectItem key={option.value} value={option.value}>
                            <div className="font-medium">{option.label}</div>
                            <div className="text-xs text-gray-500">{option.description}</div>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                {/* Name Fields */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="firstName">First Name *</Label>
                    <Input
                      id="firstName"
                      name="firstName"
                      type="text"
                      autoComplete="given-name"
                      value={signupFormData.firstName}
                      onChange={e => handleInputChange('firstName', e.target.value)}
                      placeholder="Enter first name"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="lastName">Last Name *</Label>
                    <Input
                      id="lastName"
                      name="lastName"
                      type="text"
                      autoComplete="family-name"
                      value={signupFormData.lastName}
                      onChange={e => handleInputChange('lastName', e.target.value)}
                      placeholder="Enter last name"
                      required
                    />
                  </div>
                </div>
                {/* Email Field */}
                <div className="space-y-2">
                  <Label htmlFor="email">Email Address *</Label>
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    autoComplete="email"
                    value={signupFormData.email}
                    onChange={e => handleInputChange('email', e.target.value)}
                    placeholder="Enter email address"
                    required
                  />
                </div>
                {/* Avatar generator */}
                <div className="space-y-4">
                  <Label>Create Your Avatar</Label>
                  <div className="flex flex-col sm:flex-row items-center gap-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
                    {/* Avatar Preview */}
                    <div className="flex-shrink-0">
                      <img
                        src={getCurrentAvatarUrl()}
                        alt="Avatar Preview"
                        className="w-20 h-20 sm:w-24 sm:h-24 rounded-full border-4 border-white dark:border-gray-700 shadow-lg"
                      />
                    </div>
                    {/* Avatar Controls */}
                    <div className="flex-1 space-y-3">
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <div className="space-y-2">
                          <Label htmlFor="avatarStyle" className="text-xs font-medium">Style</Label>
                          <Select value={signupFormData.avatarStyle} onValueChange={handleAvatarStyleChange}>
                            <SelectTrigger className="h-9 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent>
                              {AVATAR_STYLES.map(style => (
                                <SelectItem key={style.value} value={style.value}>
                                  <div className="font-medium">{style.label}</div>
                                  <div className="text-xs text-gray-500">{style.description}</div>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="avatarSeed" className="text-xs">Seed (Name/Text)</Label>
                          <div className="flex gap-2">
                            <Input
                              id="avatarSeed"
                              name="avatarSeed"
                              value={signupFormData.avatarSeed}
                              onChange={e => handleAvatarSeedChange(e.target.value)}
                              placeholder="Enter your name"
                              className="h-9 text-xs flex-1"
                            />
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={generateRandomSeed}
                              className="h-9 px-3 text-xs"
                              title="Generate random avatar"
                              aria-label="Random avatar seed"
                            >
                              🎲
                            </Button>
                          </div>
                        </div>
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs font-medium text-gray-600 dark:text-gray-400">
                          Avatar URL (auto-generated)
                        </Label>
                        <Input
                          id="avatarUrl"
                          name="avatarUrl"
                          value={getCurrentAvatarUrl()}
                          readOnly
                          className="h-8 text-xs bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="bg-blue-50 dark:bg-blue-900/20 p-3 rounded-lg">
                    <p className="text-xs text-blue-700 dark:text-blue-300">
                      💡 <strong>Tip:</strong> Change the seed text or click dice to generate different avatars.
                      The same seed always creates the same avatar.
                    </p>
                  </div>
                </div>
              </div>
            )}
            {/* Step 2: Security Setup */}
            {currentStep === 2 && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="password">Password *</Label>
                  <div className="relative">
                    <Input
                      id="password"
                      name="password"
                      type={showPassword ? "text" : "password"}
                      value={signupFormData.password}
                      onChange={e => handleInputChange('password', e.target.value)}
                      placeholder="Create a strong password"
                      required
                      autoComplete="new-password"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(v => !v)}
                      className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500"
                      title={showPassword ? "Hide password" : "Show password"}
                    >
                      <i className={`fas ${showPassword ? 'fa-eye-slash' : 'fa-eye'} text-sm`}></i>
                    </button>
                  </div>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Must be at least 6 characters long
                  </p>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">Confirm Password *</Label>
                  <div className="relative">
                    <Input
                      id="confirmPassword"
                      name="confirmPassword"
                      type={showConfirmPassword ? "text" : "password"}
                      value={signupFormData.confirmPassword}
                      onChange={e => handleInputChange('confirmPassword', e.target.value)}
                      placeholder="Confirm your password"
                      required
                      autoComplete="new-password"
                    />
                    <button
                      type="button"
                      onClick={() => setShowConfirmPassword(v => !v)}
                      className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500"
                      title={showConfirmPassword ? "Hide password" : "Show password"}
                    >
                      <i className={`fas ${showConfirmPassword ? 'fa-eye-slash' : 'fa-eye'} text-sm`}></i>
                    </button>
                  </div>
                </div>
                <div className="bg-blue-50 dark:bg-blue-900/20 p-3 sm:p-4 rounded-lg">
                  <h4 className="text-sm font-medium text-blue-900 dark:text-blue-100 mb-2">
                    🔒 Security Note
                  </h4>
                  <p className="text-xs sm:text-sm text-blue-700 dark:text-blue-300">
                    Your password will be securely hashed and stored. We recommend using a strong, unique password.
                  </p>
                </div>
              </div>
            )}
            {/* Step 3: AI Questionnaire Only */}
            {currentStep === 3 && (
              <div className="space-y-4">
                <div className="text-center space-y-2">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                    AI-Powered Setup
                  </h3>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Let our AI create personalized habits for you
                  </p>
                </div>

                {/* AI Questionnaire */}
                <div className="space-y-3">
                  <div className="bg-gradient-to-r from-purple-50 to-indigo-50 dark:from-purple-900/20 dark:to-indigo-900/20 p-4 rounded-lg border border-purple-200 dark:border-purple-700">
                    <div className="flex items-start space-x-3">
                      <div className="flex-shrink-0">
                        <div className="w-10 h-10 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-full flex items-center justify-center">
                          <i className="fas fa-robot text-white text-sm"></i>
                        </div>
                      </div>
                      <div className="flex-1">
                        <h4 className="text-sm font-medium text-purple-900 dark:text-purple-100 mb-1">
                          Get Personalized Habit Suggestions
                        </h4>
                        <p className="text-xs text-purple-700 dark:text-purple-300 mb-3">
                          Let our AI analyze your preferences and create custom habits tailored to your lifestyle and goals.
                        </p>
                        
                        {/* Make this button more prominent */}
                        <Button
                          onClick={() => setShowAIQuestionnaire(true)}
                          className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-medium py-3 px-4 rounded-lg shadow-md hover:shadow-lg transition-all duration-200 transform hover:scale-105 border-2 border-purple-300"
                        >
                          <i className="fas fa-brain mr-2"></i>
                          🚀 Start AI Questionnaire
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>

                <div className={`p-3 sm:p-4 rounded-lg ${questionnaireCompleted ? 'bg-green-50 dark:bg-green-900/20' : 'bg-yellow-50 dark:bg-yellow-900/20'}`}>
                  <h4 className={`text-sm font-medium mb-2 ${questionnaireCompleted ? 'text-green-900 dark:text-green-100' : 'text-yellow-900 dark:text-yellow-100'}`}>
                    {questionnaireCompleted ? '✅ AI Setup Complete!' : '🎉 Almost Done!'}
                  </h4>
                  <p className={`text-xs sm:text-sm ${questionnaireCompleted ? 'text-green-700 dark:text-green-300' : 'text-yellow-700 dark:text-yellow-300'}`}>
                    {questionnaireCompleted 
                      ? 'Great! Your personalized habits are ready. Click "Create Account" to finish.'
                      : 'Complete the AI questionnaire to get personalized habits, then click "Create Account" to finish.'
                    }
                  </p>
                </div>
              </div>
            )}
            {/* Actions */}
            <div className="flex flex-col sm:flex-row justify-between gap-3 pt-4 sm:pt-6">
              <Button type="button" variant="outline" onClick={currentStep === 1 ? onClose : handleBack} disabled={loading} className="w-full sm:w-auto h-10 sm:h-11 text-sm">
                {currentStep === 1 ? 'Cancel' : 'Back'}
              </Button>
              <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
                {currentStep < 3 ? (
                  <Button type="button" onClick={handleNext} className="w-full sm:w-auto h-10 sm:h-11 text-sm bg-blue-600 hover:bg-blue-700 text-white">
                    Next
                  </Button>
                ) : (
                  <Button 
                    type="button" 
                    onClick={handleSignupSubmit} 
                    disabled={loading || !questionnaireCompleted || disabled} 
                    className="w-full sm:w-auto h-10 sm:h-11 text-sm bg-green-600 hover:bg-green-700 text-white disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {loading ? <div className="flex items-center gap-2">
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                      Creating Account...
                    </div> : disabled ? 'Offline Mode - Signup Disabled' : questionnaireCompleted ? 'Create Account' : 'Complete AI Setup First'}
                  </Button>
                )}
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
      <AIQuestionnaireModal
        open={showAIQuestionnaire}
        onClose={() => {
          setShowAIQuestionnaire(false);
          // Don't show success message on accidental close
          // Only show success if questionnaire was actually completed
        }}
        onComplete={() => {
          setShowAIQuestionnaire(false);
          setQuestionnaireCompleted(true);
          toast({
            title: "AI Setup Complete! 🤖",
            description: "Your personalized habits have been configured based on your preferences.",
          });
        }}
      />
    </>
  );
}